using System.Globalization;
using System.Numerics;

namespace Theodicean.SharpAdb.Pairing;

/// <summary>
/// Affine point arithmetic on the twisted Edwards curve used by Ed25519/X25519
/// (<c>-x^2 + y^2 = 1 + d*x^2*y^2</c> over GF(2^255-19)). Used only to implement the SPAKE2
/// variant ADB's wireless-pairing protocol runs (BoringSSL's Curve25519-based SPAKE2, not the
/// NIST P-256/RFC 9382 variant). Arithmetic is <see cref="BigInteger"/>-based and not
/// constant-time: acceptable here because this only runs once per human-mediated pairing
/// exchange, not as a repeated signing oracle.
/// </summary>
internal readonly struct Edwards25519Point
{
    /// <summary>Field prime, 2^255 - 19.</summary>
    private static readonly BigInteger P = BigInteger.Pow(2, 255) - 19;

    /// <summary>Order of the prime-order subgroup generated by <see cref="BasePoint"/>.</summary>
    internal static readonly BigInteger Order =
        BigInteger.Pow(2, 252) + BigInteger.Parse("27742317777372353535851937790883648493", CultureInfo.InvariantCulture);

    // d = -121665/121666 mod p.
    private static readonly BigInteger D = Mod(-121665 * ModInverse(121666, P), P);

    private static readonly BigInteger BaseX =
        BigInteger.Parse("15112221349535400772501151409588531511454012693041857206046113283949847762202", CultureInfo.InvariantCulture);
    private static readonly BigInteger BaseY =
        BigInteger.Parse("46316835694926478169428394003475163141307993866256225615783033603165251855960", CultureInfo.InvariantCulture);

    internal static readonly Edwards25519Point BasePoint = new(BaseX, BaseY);
    private static readonly Edwards25519Point Identity = new(BigInteger.Zero, BigInteger.One);

    private readonly BigInteger _x;
    private readonly BigInteger _y;

    private Edwards25519Point(in BigInteger x, in BigInteger y)
    {
        _x = x;
        _y = y;
    }

    /// <summary>
    /// Unified (complete) Edwards addition law. Valid for doubling and for the identity element,
    /// so callers never need special-case handling.
    /// </summary>
    internal Edwards25519Point Add(in Edwards25519Point other)
    {
        // ReSharper disable InconsistentNaming
        var x1y2 = _x * other._y;
        var x2y1 = other._x * _y;
        var y1y2 = _y * other._y;
        var x1x2 = _x * other._x;
        var dxxyy = Mod(D * x1x2 % P * (_y * other._y % P), P);
        // ReSharper restore InconsistentNaming

        var x3 = Mod((x1y2 + x2y1) % P * ModInverse(Mod(1 + dxxyy, P), P), P);
        var y3 = Mod((y1y2 + x1x2) % P * ModInverse(Mod(1 - dxxyy, P), P), P);
        return new Edwards25519Point(x3, y3);
    }

    private Edwards25519Point Negate() => new(Mod(-_x, P), _y);

    internal Edwards25519Point Subtract(in Edwards25519Point other) => Add(other.Negate());

    /// <summary>Double-and-add scalar multiplication. <paramref name="scalar"/> must be non-negative.</summary>
    internal Edwards25519Point Multiply(BigInteger scalar)
    {
        var result = Identity;
        var addend = this;
        while (scalar > 0)
        {
            if (!(scalar & 1).IsZero)
                result = result.Add(addend);
            addend = addend.Add(addend);
            scalar >>= 1;
        }
        return result;
    }

    /// <summary>
    /// Standard Ed25519 compressed point encoding: <see cref="_y"/> little-endian over 32 bytes,
    /// with the top bit of the last byte set to the low bit (parity) of <see cref="_x"/>.
    /// </summary>
    internal byte[] Encode()
    {
        var bytes = ToLittleEndian32(_y);
        if (!(_x & 1).IsZero)
            bytes[31] |= 0x80;
        return bytes;
    }

    /// <summary>
    /// Decodes a standard 32-byte compressed Ed25519 point, validating it lies on the curve.
    /// Mirrors BoringSSL's <c>x25519_ge_frombytes_vartime</c> contract: returns <see langword="false"/>
    /// for a point not on the curve instead of throwing, since a malicious/buggy peer message is an
    /// expected failure mode of the wire protocol, not a programming error.
    /// </summary>
    internal static bool TryDecode(in ReadOnlySpan<byte> encoded, out Edwards25519Point point)
    {
        point = default;
        if (encoded.Length != 32)
            return false;

        var signBit = (encoded[31] & 0x80) != 0;
        Span<byte> yBytes = stackalloc byte[32];
        encoded.CopyTo(yBytes);
        yBytes[31] &= 0x7F;

        var y = FromLittleEndian(yBytes);
        if (y >= P)
            return false;

        // x^2 = (y^2 - 1) / (d*y^2 + 1) mod p
        var y2 = y * y % P;
        var numerator = Mod(y2 - 1, P);
        var denominator = Mod(D * y2 + 1, P);
        var x2 = Mod(numerator * ModInverse(denominator, P), P);

        if (!TrySqrtMod(x2, out var x))
            return false;

        if (x.IsZero && signBit)
            // There is no negative representative of zero; a set sign bit with x=0 is invalid input.
            return false;

        if (!(x & 1).IsZero != signBit)
            x = Mod(-x, P);

        point = new Edwards25519Point(x, y);
        return true;
    }

    /// <summary>
    /// Reduces a 64-byte little-endian integer (e.g. a SHA-512 digest or 64 random bytes) modulo
    /// <see cref="Order"/>, matching BoringSSL's <c>x25519_sc_reduce</c>.
    /// </summary>
    internal static BigInteger ReduceModOrder(in ReadOnlySpan<byte> bytes64)
    {
        if (bytes64.Length != 64)
            throw new ArgumentException("Expected 64 bytes", nameof(bytes64));

        return Mod(FromLittleEndian(bytes64), Order);
    }

    // p ≡ 5 (mod 8) for 2^255-19, so sqrt(a) = a^((p+3)/8) when a is a quadratic residue,
    // optionally adjusted by the fixed square root of -1 (RFC 8032's decoding algorithm).
    private static bool TrySqrtMod(in BigInteger a, out BigInteger root)
    {
        var candidate = BigInteger.ModPow(a, (P + 3) / 8, P);
        if (Mod(candidate * candidate - a, P).IsZero)
        {
            root = candidate;
            return true;
        }

        var sqrtMinus1 = BigInteger.ModPow(2, (P - 1) / 4, P);
        candidate = Mod(candidate * sqrtMinus1, P);
        if (Mod(candidate * candidate - a, P).IsZero)
        {
            root = candidate;
            return true;
        }

        root = default;
        return false;
    }

    private static BigInteger Mod(in BigInteger value, in BigInteger modulus)
    {
        var result = value % modulus;
        return result.Sign < 0 ? result + modulus : result;
    }

    private static BigInteger ModInverse(in BigInteger value, in BigInteger modulus)
    {
        // Fermat's little theorem: modulus is prime, so inverse = value^(modulus-2) mod modulus.
        return BigInteger.ModPow(Mod(value, modulus), modulus - 2, modulus);
    }

    private static BigInteger FromLittleEndian(in ReadOnlySpan<byte> bytes) =>
        new(bytes, isUnsigned: true, isBigEndian: false);

    private static byte[] ToLittleEndian32(in BigInteger value)
    {
        var result = new byte[32];
        if (!value.TryWriteBytes(result, out var written, isUnsigned: true, isBigEndian: false) || written > 32)
            throw new InvalidOperationException("Field element did not fit in 32 bytes");
        return result;
    }
}
